src/styles/vars.css

Simple fix. Can't include css-extend variables in `:root`.

Fixed css-extend issue

---

src/client/features/view/cy/events/hover.js

#69 - I implemented a quick fix to the hover issue, which simply prevents the event from applying the hover style to a parent if its expanded.

Disabled hover style when parent node  is expanded

---

src/client/features/view/components/graph/index.js
src/client/features/view/components/menu/search.js
src/client/features/view/components/tooltips/formatArray.js
src/client/features/view/components/tooltips/generateContent.js
src/client/features/view/components/tooltips/metadataTip.js
src/client/features/view/components/tooltips/publications.js
src/client/features/view/config.js
src/styles/features/view/toolTip.css

- #187 -  Fixed tooltip ordering. All the tooltips will always maintain the order of the values. 
- #180 -  Replaced Publication Ids with publication names
- #189 - Removed Datasource/Display Name from the tooltip
- #213 - Database References and field-values have been formatted as comma separated lists
#212 - Set the Overlay Padding to 0

Implemented tooltip and search suggestions

---

package.json
src/client/cytoscape-extensions.js
src/client/features/view/components/tooltips/metadataTip.js
src/client/features/view/cy/events/click.js
src/client/features/view/cy/events/expandCollapse.js
src/client/features/view/cy/events/index.js
src/client/features/view/cy/events/showTooltip.js

- #215 - Double-click has been mapped to expand/collapse
- #215 - Single click now summons the tooltip
- #215 - Tooltip does not appear when a user drags the node around
- #176 - Tooltip now works in Firefox 
- #224 - Alignment issue was related to the popper.js extension and has been resolved. Changes will be applied when the Popper PR is merged cytoscape/cytoscape.js-popper#10 
- Tooltip also now resizes based on zoom level.

Node Event Binding Changes and Tooltip alignment changes

---

src/styles/features/search.css

This bug appears on Harsh and Geoff's browsers but not on mine for some reason. This should fix it.

Fixes search bug on some browsers where scrollbar always appears beneath tabs.

---

src/client/common/cy/layout/index.js
src/client/features/view/components/menu/index.js
src/client/features/view/index.js

Added back in code, now to the menu bar, that saves a layout to the database when it is changed in admin mode. In the current development build saving layouts doesn't work.

Readded code that saves layout changes to the database

---

src/server/database/saveDiffs.js
src/server/database/update.js

- Reordered promise creation in saveDiffs.js createNewLayout so that the call to getLatestPositions does not retrieve the id for the layout about to be created
- Changed a use of throw to Promise.reject in an async function

Resolved Race Condition + corrected error creation

---

package.json

Currently the development build on Jenkins fails because `uglify-js` doesn't support some ES6 syntax. Updating the uglify version to the beta fixes the production build.

Update to beta version of uglify JS to support ES6 syntax

---

package.json
src/server/config.js

Sets uglify version back to 0.4.6 (#256), and resets port to 3000 (#255).
Should handle #264 as well.

Reverts port and uglify changes

---

src/client/common/cy/layout/index.js
src/client/features/view/components/menu/index.js
src/client/features/view/index.js

Addresses issues in #263, namely
- Change ‘Rearrange Entities’ to ‘Arrange Display’
- Update display descriptions to be more descriptive
- Make layouts option available in edit mode only
- Add a reset button to the menu bar with the default being human created layouts, and if there is none, CoSE-Bilkent

Disabled extra layouts in view mode

---

src/client/common/cy/events/click.js
src/client/common/tooltips/config.js
src/client/common/tooltips/generateContent.js
src/client/common/tooltips/metadataTip.js
src/styles/features/view/toolTip.css

.This PR implements all the suggested tooltip UI changes made during the Tuesday meeting with Gary. 
closes #226 
- Removed type field from tooltip, but kept the type name
- Changed `approved name` to `name`
- Changed Database References` to Links
- Changed default position to `bottom`
- Assigned a max height to tooltip
closes #261
The tooltip expand button has been removed. Comments, Links, and Synonyms now have their options to individual expand and close data.

Tooltip Revision 3 

---

src/styles/features/view/menuBar.css

Fixed an issue with padding in Firefox, and added a nasty patch job to make the menu bar behave a little better in Safari. It would seem Safari doesn't bother calculating the width of inner components of absolutely positioned divs, meaning the toolbar ends up looking like this in Safari:
The fix I made here doesn't fix that, but makes the animations work smoothly, whereas they used to be jerky.
Any ideas about how to fix the wide toolbar in Safari?

Small browser compatibility fixes

---

src/client/common/cy/revisions/generateImages.js
src/server/graph-renderer/renderImage.js

#318 - Fixed spacing with the preview images, so the snapshot images are now a closer representation of the layout revison.

DEMO : Fixed Layout Revision Previews

---

src/client/common/tooltips/formatArray.js
src/client/common/tooltips/generateContent.js
src/client/common/tooltips/publications.js

I reformatted all the comments in the tooltips folder to follow the JSDoc comment style recommended by max. These formatted comments also include basic Input/Output example to convey the purpose of future users.

Reformatted tooltip code comments to match the JSDoc format

---

src/client/common/config.js
src/client/common/tooltips/generateContent.js

I re added the display name field to the tooltip as it contained information that was important for certain nodes.  @jvwong  highlighted such a case here #327

DEMO : Re added display name back to the tooltip

---

package.json
src/client/common/cy/events/click.js
src/client/cytoscape-extensions.js
src/client/features/view/components/graph/contextMenu.js
src/client/features/view/components/graph/index.js
src/styles/features/view.css
src/styles/features/view/contextMenu.css

#321 
Jeff suggested adding a context menu to allow for additional options beyond expand/collapse and show tooltip.
I have mocked up a rough tooltip using the cytoscape-cxtmenu extension used in factoid to just demonstrate the features potential use case. 
@jvwong @d2fong  @maxkfranz , any suggestions on potential design changes. 
Note : Merging this into the 'fun' branch just to seek feedback on the idea of having a context menu.

Context Menu

---

src/client/common/components/base-network-view/base-network-view.js
src/client/common/components/base-network-view/config/index.js
src/client/common/components/base-network-view/config/menus/file-download.js
src/client/features/interactions/index.js

Changes made to the toolbar menus from interactionViewCombined
- Fetch information form Uniprot for the additional information menu
- Download limited to the PNG and SIF file types for interaction networks
- SIF is built from interactions currently visible in the view instead of fetched from PC in the interaction viewer 
- Removed expand/collapse nodes button from tool bar in the interaction viewer

Interation view toolbar changes

---

src/client/common/cy/events/click.js
src/client/common/cy/events/index.js
src/client/common/cy/tooltips/format-content.js
src/client/common/cy/tooltips/index.js
src/client/features/interactions/index.js
src/styles/features/view/toolTip.css

Includes changes from issue #473 and #466 and a bug that was noticed during work on these issues:
- Tool tips are now alway located close to the edge. Changes to tooltips.index, based the distance from the edge off of the current zoom which fixed the issue. 
- Noticed a bug in the behaviour of the tooltips. If the user clicked on a edge,node,edge or node,edge,node the new tooltip would not show. This was fixed by the changes made to click.js
- Put the Pathway Commons mediator ids to be under their own heading , 'Detailed Views',  this involved changes to format-content.js and a small change in interactions/index.js(changing metadata in interactionsMetadata)
- Added Pubmed links to edge tooltips using the Pubmed ids in the SIF file, changes made to interactions/index.js

Changes to tooltips (Issue #473 and #466)

---

src/client/common/cy/match-style.js

The issue in #515 was caused by inconsistent formats of geneSynonyms in the nodes data. On most networks geneSynonyms is stored as an array of strings (left as an empty array if none), on some it is left undefined and on others it is stored as an object (left as an empty array if none). This cassued the issue as it meant that .toUpperCase was called on a object instead of a string. 
The fix is to only concatenate geneSynonyms with label if it is an array.

Issue #515 fix

---

src/client/common/cy/index.js
src/client/features/interactions/index.js

Changes from issue #465. Passed in minZoom value to allow larger networks to be fully displayed and changed the initial handling of the network to fix the case where all the nodes that did not have a binding edge would not be given an intial layout.

Network layout fix

---

src/client/features/interactions/index.js

The filter options that would have no associated nodes/edges are not removed from the filter menu(issue #572 ).

Remove useless filter options

---

src/client/common/cy/tooltips/format-content.js
src/client/features/interactions/index.js

Moved Reactome MEDIATOR_IDS to be included in 'Detailed Views' as discussed in issue #606.

Reactome MEDIATOR_IDS included in 'Detailed Views'

---

src/client/common/config.js
src/client/features/interactions/index.js
src/client/features/search/index.js
src/client/features/search/landing-box.js
src/client/services/server-api/index.js
src/styles/features/interactions.css
src/styles/features/search.css
src/styles/index.css

I made a branch and merged all the changes I had that where waiting for PRs into 1 branch.  There is no need to merge PR #608 if we merge this.
Changes in this PR as a full are:
- Support case where user enters more than 1 recognized gene with both the landing box and interaction viewer (issue #520)
- Move away from uniprot dependency to support wider range of genes by changing database used by landing box (issue #574).
- Refactor landing box into separate component (issue #627)
Changes to interactions/index.js:
- All networkMetadata now fetched by ServerAPI. getGeneInformation
- Only trim the network if the number of found ids = to the number of quired genes (this stops the case where the quried gene may be removed by trimming)
- findId() removed and changes to parse are because ids are …

Fully Updated Landing Box and Interaction Viewer

---

src/server/enrichment-map/emap/generateGraphInfo.js

related #563
changed input format to generateGraphInfo to the same as the output of enrichment service
e.g.
```
{
"GO:0006354": {
"pValue": 1,
"t": 124
},
"GO:0006368": {
"pValue": 0.999,
"t": 100,
"q": 1,
"qAndT": 1,
"qAndTOverQ": 1,
"qAndTOverT": 0.01,
"tType": "BP",
"tGroup": 5,
"tName": "transcription elongation from RNA polymerase II promoter",
"tDepth": 1,
"qAndTList": [
"AFF4"
]
}
}
```

allow emap to accept data with pathway ID

---

src/server/enrichment-map/gene-validator/index.js

related to #559 
- change duplicate to object
- each convertedAlias in duplicate is followed by a list of initialAliases 
output:
```
{
...
"duplicate": [
{"AFF4": ["AFF4", "Q9UHB7"]},//  {<convertedAlias1>: [<initialAlias11>, ...]
{"TP53": ["TP53", "P04637"]} //  {<convertedAlias2>: [<initialAlias21>, ...]
],
...
}
```

change validator duplicate format

---

src/client/features/interactions/index.js
src/client/features/search/index.js
src/client/features/search/landing-box.js

Changes from issue #652.
- Change the initial timing of the network to make sure one interaction type is always enabled.
- Remove the code to cut out the landing box when no pathway search results are found.
- Move some left over code from search to landing box.

Always show the landing box and change to how the initial trim is done.

---

src/server/enrichment-map/emap/generate-graph-info.js
src/server/enrichment-map/emap/intersect.js
src/server/enrichment-map/gene-validator/index.js

related to #635
in gene-validator/index.js and generate-graph-info.js, O(n^2)->O(n)
- use sets for unrecognized and duplicate instead of nested loops
in intersect.js, O(n^2) -> O(n)
- when counting the intersections pairwise, concatenate, sort, count consecutive duplicates

reduce runtime in distiller services

---

src/server/enrichment/analysis/enrichment.js
src/server/enrichment/validation/index.js
src/server/enrichment/visualization/generate-graph-info.js
src/server/routes/enrichment-rest.js

- check array type for parameter 'genes' in validation and analysis services, related to #544 
- check number type explicitly, boolean to number conversion is not allowed, related to #716
- allow 1 for true, 0 for false, no other number to boolean conversion is allowed, related to #716
- delete useless code, no need to check for "pathwayId" field in visualization service input

boolean number conversion, array type checking

---

src/server/pathway-commons/search/index.js

Not sure what caused the issue, though I think it is the fact that undefined was being passed to JSON.parse(JSON.stringify(userOptions)) at https://github.com/PathwayCommons/app-ui/blob/development/src/server/enrichment/validation/index.js#L44 (but it was not change recentlly) casued the search to break and this fixes it.

Fix search

---

README.md

New content includes instructions to run app locally. Code from: https://raw.githubusercontent.com/PathwayCommons/app-ui/development/README.md

#753 Update README in master branch

---

src/client/features/interactions/index.js
src/client/features/search/landing-box.js

In search info box, the text and link of HGNC are changed (ref. #756 ):
1. Text: "HGNC Symbol"
2. URI format: `http://identifiers.org/hgnc.symbol/<HGNC approved symbol>`
Before:
<br/>
<br/>
After:

Infobox text and URI change

---

src/client/features/search/landing-box.js
src/client/services/server-api/index.js

ref #768 
Before:
`ServerAPI.pcQuery('search', {q:entry,entry:'entityreference'})`
After:
`ServerAPI.pcQuery('search', {q:entry,type:'entityreference'})`

Landing box pcQuery uses incorrect parameter name

---

src/client/services/server-api/index.js

Content type is changed to `application/json`
Request body is changed to JSON format.
ref: #767

Correct content-type in geneQuery

---

src/client/services/server-api/index.js

Ref: #767 
`padding` in the query function is unused after the content-type is changed to `application/json`

Remove unused value from geneQuery

---

src/client/common/cy/events/show-tooltip.js
src/client/common/cy/tooltips/format-content.js
src/client/common/cy/tooltips/index.js
src/styles/features/view/toolTip.css

Changed Location of Link in tooltip and improved link text so users know what they are clicking on. Based on Discussion in #483
Example Tooltip Before:
Example Tooltip After:

Modified tooltips to include PC Search Link

---

src/client/services/server-api/index.js

Text input field accepts multiple tokens of the form `db:id` (ref:#790):
<br/>
<br/>
The procedure is:
1. Remove all prefix db:id in input string
2. Remove extra spaces
3. Search ids as before.

Text input field allows multiple tokens

---

src/client/features/view/index.js

Refs #779 .
When pathway commons attempts to load a network with no nodes or edges, the following message will be displayed:

Added fix for empty network view

---

src/styles/features/view/sidebarMenu.css

Ref: #817 
The side menu is now available in small width.

Interaction side menu style changes

---

test/server/database/testSaveDiffs.js
test/server/database/testUpdate.js

Re: https://github.com/PathwayCommons/app-ui/issues/811#issuecomment-397332484
Fixes failing db tests for `optionally accepts a callback`. There was some extra null parameter.

db tests with callback had extra param

---

src/client/common/cy/tooltips/format-content.js
src/client/common/cy/tooltips/index.js
src/client/common/cy/tooltips/publications.js
src/server/graph-generation/biopax-metadata/index.js

Some pid pathways have entities with `null` data array. This was causing the tooltip display to throw an error in console.
This PR should fix some errors caused by code assuming data array was`[]` not `null`

Fixed Error with tooltip Display

---

src/client/features/search/landing-box.js

Ref: #856  #864
- Gene Card link is removed
- Uniprot is changed to UniProt

Update landing page links

---

src/server/enrichment/visualization/generate-graph-info.js
src/server/enrichment/visualization/generate-info.js
src/server/routes/enrichment-rest.js

Ref: #845 
Each node in the graph in visualization service includes number of genes. Swagger is updated correspondingly.

Visualization service update

---

src/client/features/enrichment/index.js
src/client/features/enrichment/token-input.js
src/styles/features/enrichment.css

- Click anywhere on screen to close input box
- Synchronize the opening and closing of unrecognized token feedback box
- Open input box (and unrecognized box if invalid tokens exist) when network is loaded
***Remaining issue: clicking/trying to highlight the unrecognized tokens box will cause the input box to lose focus, and, as a result, both boxes close.

Collapse input box #917

---

src/client/features/pathways/cy/events.js
src/client/features/pathways/cy/expand-collapse-cue.js
src/client/features/pathways/cy/layout.js
src/client/features/pathways/cy/pathways-stylesheet.js
src/styles/features/pathways/tooltip.css
src/styles/vendor/tippy.css

- adds expand collapse cue for each node on hover.  
- uses tippy tooltips to implement the cue
- 'meta edges' from the expand collapse library are dashed to communicate that they are 'meta edges'
- many subtle complexities and edge cases are handled but there are probably more that I can't think of right now.

Expand collapse cue

---

package.json
src/client/features/enrichment-map/token-input.js
src/client/features/enrichment/token-input.js
src/client/services/server-api/index.js
src/server/cache.js
src/server/enrichment/validation/index.js

- Update package.json to have `npm run ci` shortcut so it's easy to run the CI tests locally before making a PR.
- Remove cases where promises have their error cases consumed without rethrowing.
- Revise the caching mechanism to selectively remove entries for failed promises.
- Remove enrichment server-side timeout and dummy data returned on failure case.
Supersedes #957
@d2fong Does this make sense with your enrichment-map=>enrichment changes?

Jeff and Max : caching changes and misc. changes

---

src/client/features/interactions/index.js
src/client/features/search/entity-info-box.js

- Show the button to open the interactions viewer only when in dev mode (e.g. watch).
- Fix : Clean up the entity list sent through the URL: Just use a simple comma-separated string.
Note: The button would not be visible on appsbeta.pathwaycommons.org.  Another flag would be needed independent of dev/prod for that.  This should suffice for local development of the interactions viewer, and the flag check can be removed completely when it's ready to be released.

Make the interactions viewer button available when `NODE_ENV=development`

---

src/server/routes/enrichment-rest.js

- add geneSet to API documentation
- correct 'gene-count' to 'geneCount' in documentation

add geneSet to doc, fix spelling #956

---

src/client/features/enrichment-map/index.js
src/styles/features/enrichment.css
src/styles/features/pathways.css

Changes for enrichment-map route
- fix styling for enrichment app after rerouting and refactoring
- off click input box to close 
- open toolbar and sidebar after an initial network has been loaded
- fix positioning of search box in toolbar
- app bar moves to the left if screen is width is decreased
Initial:
After loading:

Enrichment Style Changes after refactor

---

src/client/features/enrichment/enrichment-tooltip.js

- alphabetize gene lists in node tooltips to allow user to easily look for a specific gene

Sort gene lists in tooltip #1010

---

src/client/features/paint/pathway-node-metadata.js
src/client/features/pathways/index.js
src/client/features/pathways/pathway-node-metadata.js

refs #961
Also refs another issue about not showing the pc search link button in the tooltip if the search query would be empty
Also refs another issue about not loading the appbar/toolbar if the pathway is not loaded yet.

Empty string tooltip

---

src/client/features/enrichment/index.js

Enrichment App
- use loading spinner
- fit loaded network to available space on screen
- hard code 'network-sidebar-open' to true since side menu will always be open when a network is loaded and a layout is applied. Before, value of 'false' was being passed when loading the network because of (activeMenu: 'closeMenu') in the constructor

use loading spinner and fit network to screen #1027

---

src/styles/features/pathways/sidebar-menu.css

#1024
- on close, slide the sidebar further to the right to fully hide it
- now if you hover in right corner, nothing shows up
Previously, not all of the sidebar was being hidden, it was just made to be opaque.
Previous view when opacity changed to '1' :

hide 'close sidebar' button #1024

---

src/client/features/enrichment/token-input.js
src/styles/features/enrichment.css

- example input for enrichment set to: "tyr, oca2, tyrp1, slc45a2"  
(chosen because of quick loading time and variation in node sizes and colours)
- text colour change on hover 'e.g.' 
- 'e.g.' disappears once any text is typed into input box
- input box opens when example input is selected
Resulting Network

Enrichment example input #1020

---

package-lock.json
package.json
src/client/common/datasource-url-map.js
src/client/features/pathways/index.js
src/client/models/pathway/pathway-model.js
src/styles/features/pathways/app-bar.css

Fixes #1018 
Fixes #930
Reversed the order of `Pathway name | Datasource` => `Datasource | Pathway name`.
Removed "Unknown Title" text if it were to appear.
The map should be correct for all datasources as of right now, but there is also a string similarity calculation included as backup in case the names change in future.

Added links to databases to pathway view title

---

src/client/features/enrichment/enrichment-menu.js
src/client/features/enrichment/index.js

Refs: #984 
- Store slider value in main component
- When show/hide side menu button is clicked, the network will not reload
- Slider value matches its position.

Match enrichment slider position on show/hide button clicked

---

src/client/router.js
src/views/index.html

refs #1043
Currently, all non-api routes render index.html.  The problem when rendering index.html was that the corresponding js and css assets were specified as a relative path.  Leading to the browser trying to get assets like /search/bundle.js when the specified path was /search/.  These assets would not be found leading to the broken behaviour.  
This fix changes the path of the required assets in index.html

index.html uses root path to get css/js bundles

---

src/client/common/components/cytoscape-network.js
src/client/features/enrichment/index.js
src/client/features/interactions/index.js
src/client/features/paint/index.js
src/client/features/pathways/index.js

- create a cytoscape network component that handles componentWillMount/unMount logic.  
- parent components pass a 'onMount' prop that is called after the network component mounts
- the onMount prop is usually a server call to get some cytoscape json which is then loaded into cytoscape
@maxkfranz thoughts on this?

create cytoscape network component

---

src/client/features/search/entity-info-box.js
src/styles/features/entity-landing-box.css

Since it looks like a normal search result, the user may be more likely to click it.
Preview:

Make the SIF viewer link similar to all the other viewer links

---

src/client/features/interactions/cy/interactions-stylesheet.js

- selected nodes are blue
- selected edges have opacity 1, z-index 999

add node and edge selected styles

---

src/styles/features/search.css

fix minor search css quirks

---

src/client/features/interactions/index.js
src/client/features/interactions/interactions-edge-tooltip.js
src/client/features/search/entity-info-box.js

refs #1105 
- interaction listing and title 
- interaction tooltip link outs

Iss1105 - Misc user feedback

---

src/client/features/enrichment/token-input.js
src/client/features/search/query-entity-info.js
src/server/external-services/gprofiler/gconvert/index.js
src/server/external-services/pathway-commons.js
src/server/routes/enrichment/index.js
test/server/enrichment/validation/validation-test.js

Relates to #1103: validation
- updated validation tests that were always returning 'pass'
- validation service returns a plain `alias` object 
- accommodating changes for dependencies in client

Iss1103 part b: validation api

---

src/config.js
src/models/entity/summary.js
src/server/external-services/hgnc.js
src/server/external-services/ncbi.js
src/server/external-services/uniprot.js
src/server/routes/index.js
src/server/routes/summary/entity/index.js
src/server/routes/summary/index.js
test/server/summary/summary-entity-search-test.js

Refs #1104, part one.
- simple model/definition for 'entity summary' 
- external services for fetch from HGNC, NCBI Gene and UniProt 
- service to create summaries from query string (q):
- example for `q=tp53 is an important gene`
```json
{
"tp53": {
"dataSource": "http://identifiers.org/ncbigene/",
"displayName": "tumor protein p53",
"localID": "7157",
"description": "This gene encodes a tumor suppressor protein containing transcriptional activation, DNA binding, and oligomerization domains. The encoded protein responds to diverse cellular stresses to regulate expression of target genes, thereby inducing cell cycle arrest, apoptosis, senescence, DNA repair, or changes in metabolism. Mutations in this gene are associated with a variety of human cancers, including hereditary cancers such …
```

Moving 'info' data fetch to server

---

package-lock.json
src/config.js
src/server/routes/index.js
src/util/fetch.js
src/util/promise.js

- use bluebird timeout to prevent continuously waiting on requests when the corresponding external services may be down
- add a fetch timeout config value (default 5 seconds)
- tested by replacing the ncbi url with 'http://localhost:3000/api/test' which waits 10 seconds before sending a response, the request successfully timed out and logs the following error: 
`error:   TimeoutError in ncbi fetchByGeneIds: operation timed out` Not sure if there is a better way to test the behaviour.
- from my somewhat limited testing, the client doesn't hang anymore when the server takes more than 5 seconds to respond

add timeouts for fetch requests

---

src/client/features/enrichment/token-input.js
src/config.js
src/server/external-services/gprofiler/gconvert/index.js
src/server/index.js
src/server/routes/enrichment/index.js
src/server/routes/summary/entity/index.js
src/server/routes/summary/index.js
test/server/enrichment/validation/validation-test.js

- refs #1131: Basically using config constants for database data collections everywhere in the validation code, tests and the code on client / server that eventually calls `validatorGconvert` with a `target` parameter
- added-back  code by @maxkfranz  for express middleware error handling
- related simplifications of express endpoint `catch` handlers

Iss1131 pt1 : Using constants, MIRIAM collection namespaces 

---

src/server/external-services/pathway-commons.js

refs #1139 - using quick-lru has `delete()` function.

Changing cache delete syntax

---

src/client/features/search/entity-summary-box.js
src/models/entity/summary.js
src/server/external-services/hgnc.js
src/server/external-services/ncbi.js
src/server/external-services/uniprot.js
src/server/routes/summary/entity/index.js
test/server/summary/hgnc/entity-summary-TP53.json
test/server/summary/hgnc/entity-summary-test.js
test/server/summary/ncbi/entity-summary-7157.json
test/server/summary/ncbi/entity-summary-test.js
test/server/summary/uniprot/entity-summary-Q99988.json
test/server/summary/uniprot/entity-summary-test.js

refs #1132 
- Use config constants  for namespaces
- Renamed EntitySummary model  attributes:
- `dataSource` --> `namespace`
- `xref` --> `xrefLinks`
- `localID` --> `localId`
- `entitySearch()` service returns `{"query": <token>, "summary": <EntitySummary>}` 
- UI update for Summary box

Iss1132 entity summary updates

---

src/client/features/search/index.js

I think this is a React related requirement for camelCasing.

Input box attribute typo for maxLength

---

README.md
src/config.js
src/server/routes/factoids/index.js

This is to use new factoid api: api/document/sbgn instead of calling the factoid biopax/sbgn converters directly (and having an extra convertion step and config./env. option).

Makes #1193 work once PathwayCommons/factoid#395 works.

---

src/util/fetch.js
src/util/promise.js

refs #1211 - Enabling a `timeout` in fetch opts that defaults to config value `FETCH_TIMEOUT`.

Added timeout opt to fetch

---

src/server/routes/search/search.js

refs #1215 where duplicate xref being added to `xrefLinks`. Simple check before adding.

Simple check for existing uniprot xref

---

src/client/features/enrichment/enrichment-tooltip.js
src/config.js
src/server/external-services/pathway-commons.js
src/server/routes/enrichment/visualization/index.js
src/server/routes/pathway-commons-router.js
src/styles/common/cytoscape-tooltip.css
src/util/fetch.js
src/util/index.js
src/util/promise.js
test/server/enrichment/visualization/visualization-test.js
test/server/pathways/pathways-network-generation.js

The only major change is to [server/routes/enrichment/visualization/index.js](https://github.com/PathwayCommons/app-ui/compare/development...jvwong:iss1202_pathway-linkout?expand=1#diff-2f8d7aae9804307468d4fa6ea41b15c2)
- To fetch a url for a pathway
- reuse our `xref2Uri` service
- If it times out, fall back to the original method to construct URI originally in client/tooltip  
- To this end, exposed `TimeoutError`; might be useful in future #1210 
- Append `namespace` and `uri` fields  to service output object
- Accommodating changes in the client/tooltip
refs #1202

Iss1202: Enrichment pathway links

---

src/client/features/enrichment/cy/index.js

hovering over a node no longer does anything in the enrichment app

remove hover node events for enrichment

---

src/client/features/interactions/cy/index.js

When there is more than 1 source node, use a different layout (cose-bilkent) to get a better sense of the network topology

use cose-bilkent when there is more than 1 source node for the interactions app

---

src/client/features/enrichment/cy/index.js

- fixes the enrichment layout from failing when there are only disconnected nodes e.g. enrichment/tp53

fix enrichment layout bug where the first layout bb would be 0 height width when there are only disconnected nodes

---

src/styles/features/entity-landing-box.css

Missing prop for ellipsis on gene display name.
refs #1242.

Gene display name ellipsis

---

src/client/common/components/error-message.js
src/client/features/search/gene-results-view.js
src/client/features/search/index.js
src/client/features/search/pathway-results-view.js
src/styles/common/error-message.css
src/styles/common/index.css

Refs #1210.
There are five cases handled.
- Initial load
- Body currently displays 'Pathway Count (0)' and datasource selector. Instead:
- Unknown URL path
- Same as before: ![image](https://user-images.githubusercontent.com/4706307/51267328-71171f00-198b-11e9-8e38-9b9e0c3e9132.png)
- No pathway hits
- Body currently displays 'Pathway Count (0)' and datasource selector. Instead: 
- Fetch: Timeout
- Currently just hangs. Instead: 
- Fetch: Error
- Currently just hangs. Instead:

Error handling and user notification: Search

---

src/client/features/search/index.js
src/client/features/search/pathway-results-view.js
src/server/external-services/pathway-commons.js
src/server/routes/search/search.js

- Use the PC supported web service to get datasource information in place of hard-coded mapping file
- Integrate required datasource info for  searchHits directly into search response from server
Refs #1296

Swapping out Datasources file by returning info in search results.

---

src/config.js
src/server/external-services/pathway-commons.js
src/server/routes/pathway-commons-router.js
test/server/enrichment/visualization/visualization-test.js
test/server/pathways/pathways-network-generation.js
test/server/pathways/sample-cyjson-out.json

Swaps out the web service endpoint underlying `xref2Uri` that maps an xref (db, id) to URI. In particular, making *minimal* changes to replace  `http://www.pathwaycommons.org//pc2/miriam/uri/{db}/{id}` for `http://biopax.baderlab.org/xref/`.
Refs #1221.

Using the BioPax Suggester implementation

---

src/client/features/enrichment/enrichment-tooltip.js

On fetch errors from GO / Reactome, disable the loading spinner and display minimal available info rather than hang.
Refs #1291

Set minimal tooltip information on error.

---

src/client/features/interactions/cy/index.js
src/client/features/interactions/interactions-node-tooltip.js

Defend against errors in fetching tooltip data or when data has not yet been returned by server. 
In each case, displays tooltip (label + link to /search).
Refs #1292

Providing minimal node tooltip data; Swallow fetch error

---

src/server/routes/pathways/generate-pathway-json/biopax-metadata/index.js

This addresses a bug #1309 in which xrefs lacking both db and id fields were being considered.  This PR only considers those with both keys.

Check for existence of valid xref

---

src/client/features/interactions/interactions-edge-tooltip.js

Interactions tooltip: Simply bypass errors encountered when attempting to fetch publications and show minimal data. 
Refs #1312

Interactions tooltip error fallback

---

src/client/features/interactions/interactions-edge-tooltip.js

Cleanup: Set initial state during construction/mounting rather than during render().
Refs #1316.

Interactions tooltip: Remove state calls in render

---

src/client/features/search/gene-results-view.js
src/client/features/search/index.js
src/client/services/server-api/index.js
src/styles/features/search.css

The app cards already have a `show` flag for display. This PR provides a means to 'peek' at the interactions data in order to set the interaction card `show`.
Refs #1251.
Sample data: TMCC2 FUT10 GPR65 STPG2  (TP53)

Show interactions card only when data exists

---

src/client/features/paint/index.js

Access `searchHits` rather than `pathways` key when querying the /search endpoint.
Refs #1333

Updating Painter code to catch up with change in /search response api

---

src/server/routes/factoids/index.js

Catch and forward errors for  `/api/factoids` to client.
Refs #1353.

Error handling for factoids route

---

src/client/features/interactions/interactions-node-tooltip.js

Interactions tooltip has typo in 'name' for xref.

---

.travis.yml
src/server/external-services/gprofiler/gconvert/index.js
src/server/routes/enrichment/index.js
src/server/routes/search/search.js
test/server/enrichment/validation/validation-test.js

Renamed the target database parameter selection to `namespace` and made it optional; defaults this value to `hgnc`. 
Refs #1359

Make validation target database optional  

---

src/server/index.js
src/server/routes/enrichment/visualization/update-enrichment.js

- Add code that initializes (enrichment) module before server listening
- Enrichment update module checks for already downloaded GMT files (i.e. this would happen say in development) before going to g:Profiler to download them. On a fresh install, this would result in  fresh GMT files. 
refs #1378 #1373

Enrichment checks for existing files before downloading

---

package-lock.json
package.json
src/server/routes/search/search.js

This [lucene-escape-query](https://www.npmjs.com/package/lucene-escape-query) seems to take care of most cases that break the pc server. However, doesn't appear to escape slashes so things like `AKT/AMPK` return nothing unlike `AKT\/AMPK`. 
Refs #1409

Escape special characters

---

src/client/common/components/app-card.js
src/client/features/search/gene-results-view.js

> B. App Card
> When no hyperlinks appear within sliding panel (on hover), the panel effectively blocks one from navigating to the target site (e.g. the interactions, enrichment)
The feature / Biofactoid card should be unaffected.
Ref: Component tweaks #1415 (B)

App card should linkify the sliding panel for interactions & enrichment.

---

src/client/features/search/index.js
src/client/services/server-api/index.js
src/server/routes/pathway-commons-router.js
src/server/routes/search/search.js

Retrieve the PC_URL from the server endpoint, cache in client.
Refs: #1456

Enable the client to reflect the PC URL used by the server. 

---

src/server/external-services/pathway-commons.js

Feature pathway info panel needs an organism, and it calculates this based on the genes present, but the filter didn't take into account complexes, which have null association, resulting in an error. This fix takes into account the complexes.
Refs #1458

Feature panel displayed in the presence of complexes.

---

src/client/features/pathways/index.js
src/client/features/pathways/pathway-title.js
src/client/services/server-api/index.js
src/config.js
src/models/pathway/pathway-model.js
src/server/routes/pathways/generate-pathway-json/biopax-metadata/index.js
src/server/routes/pathways/generate-pathway-json/index.js
src/styles/common/app-bar.css
src/styles/common/pc-logo-link.css
src/styles/features/pathways.css
test/server/pathways/pathways-network-generation.js

The goal here was to provide richer links from the pathway to the underlying source and evidence.
- Updates the Pathway viewer with a `PathwayTitle` component that provides:
- A link from the pathway name to the datasource landing page (when available)
- A reference to the article, when there is a direct relationship (i.e. biofactoid) 
- Other
- Refactoring `generate-pathway-json` (async/await)
Refs #1407

Pathway link: Article and data provider

---

src/client/features/search/index.js

This change is intended to properly set the PC homepage links on the Search page toolbar. I believe the issue was that setting the server URL (`PC_URL`) on the Search component - rather than state - would not trigger a re-render in React. 
TLDR: The backstory for having the client retrieve the server URL (`getPCURL()`) from the backend in the first place was to be able to build assets in a Docker image.
Refs #1470

Update search toolbar links on retrieval of PC_URL from server.
