- package.json
> Added Contributors to Package.json

- src/client/features/admin/index.js
- src/client/features/view/components/editwarning/index.js
- src/client/features/view/components/graph/index.js
- src/client/features/view/components/graph/layout/index.js
- src/client/features/view/components/index.js
- src/client/features/view/components/sidebar/index.js
- src/client/features/view/components/sidebar/menus/components/downloadOption.js
- src/client/features/view/components/sidebar/menus/fileDownload.js
- src/client/features/view/components/sidebar/menus/help.js
- src/client/features/view/cy/events/click.js
- src/client/features/view/index.js
- src/client/features/view/layout/index.js
- src/client/index.js
- src/client/services/cdc/index.js
- src/client/services/index.js
Removed '.js' in requires, replaced 'var' with 'let', and removed unnecessary commented stuff in **frontend** code
> Cleaned up code 

- src/server/index.js
- src/server/routes/databaseRoutes.js
Changed route names to dash case and lowercase
> Updated route names

- src/client/features/view/components/sidebar/index.js
- src/server/database/config.js
- src/styles/features/view/editWarning.css
- src/styles/features/view/sidebarMenu.css
Resolves many of the issues in #101
> Refactoring of sidebar mostly done. Editwarning colour changed

- src/client/features/view/components/sidebar/index.js
- src/client/features/view/components/sidebar/menus/metatdataExtension.js
- src/client/features/view/components/tooltips/metadataTip.js
- src/client/features/view/config.js
- src/styles/features/view/toolTip.css
Recently merged in pull requests #112 and #133 caused a conflict due to a revised implementation of the sidebar, which has caused the build on http://beta.pathwaycommons.org to throw an error when opening a toolbar. 
The error is caused by a new implementation of the sidebar event listeners introduced in #112. This pull request reverts some of the changes introduced by #112 to fix the bug and to get http://beta.pathwaycommons.org working again.
> Conflict Fix : Sidebar Open/Close Bug Fix

- src/client/features/view/components/graph/layout/index.js
- src/client/features/view/components/graph/layout/preset.js
- src/client/features/view/cy/events/move.js
- src/client/features/view/index.js
- src/client/services/cdc/index.js
We got basic layout saving and recalling set up. Works without any bugs. The frontend code is pretty hideous and it's not in any of the right places. I'll work on setting it up properly when I do more refactoring.
> Initial layout saving implemented. Code is gross.

- src/client/features/view/cy/events/move.js
- src/client/features/view/index.js
- src/client/services/cdc/index.js
- src/server/routes/databaseRoutes/controller.js
Also added infrastructure for eventually doing live updates. More has to be fleshed out for this to work.
> Replaced single socket.io use with fetch

- src/client/features/view/components/sidebar/menus/components/downloadDescriptions.js
- src/client/features/view/components/sidebar/menus/components/downloadOption.js
> Added more links and changed around some text in downloads menu.

- src/server/database/createTables.js
- src/server/database/heuristics.js
- src/server/database/query.js
- src/server/index.js
- src/server/routes/rest.js
Other small stylistic changes as well
> elminated race condition between server start and database table creation

- Dockerfile
- docker-compose.yml
Adding docker-compose capability.
Pulls app-ui image from automated build in [DockerHub for pathwaycommons](https://hub.docker.com/r/pathwaycommons/app-ui/).
> Adding docker-compose capability; Pulls from DockerHub automated build

- src/server/config.js
This way we can host both on the VM
> Port changed to 2000 for development

- src/client/common/cy/events/expandCollapse.js
- src/client/common/cy/events/listenAndChange.js
- src/client/common/cy/revisions/rearrangeGraph.js
- src/client/features/view/components/graph/index.js
- src/client/features/view/index.js
- src/server/routes/sockets.js
> Live updates

- src/client/common/config.js
- src/client/features/view/components/graph/index.js
- src/client/features/view/components/menu/index.js
- src/client/features/view/index.js
- src/styles/features/view/menuBar.css
> Added loader when graph hasn't loaded and fixed links

- src/client/features/view/components/menu/index.js
- src/client/router.js
- src/client/services/apiCaller/index.js
- src/config.js
- webpack.config.js
Reverts PathwayCommons/app-ui#315
> Revert "Added Base Name Option and Global Config"

- src/styles/features/view/toolTip.css
Made a minor adjustment to the font size to make it slightly more readable on smaller screens.
> DEMO : Adjusted Tooltip Font Size

- src/client/features/view/components/menu/index.js
- src/styles/features/view/menuBar.css
> Removed links in menu bar

- src/client/common/cy/events/click.js
- src/client/common/cy/events/index.js
- src/client/features/view/components/menu/index.js
- src/styles/features/view/menuBar.css
> Hid sidebar buttons on mobile and added tooltip hiding on toolbar button press

- src/client/common/components/base-network-view/base-network-view.js
- src/client/features/search/index.js
Issue #361, both of the icons now link to the about page.
> Icon feature

- src/client/common/components/base-network-view/config/menus/file-download.js
- src/client/common/config.js
Issue #373. All download options now appear at once. Also removed hidden option from downloadTypes as it is no longer used.
> All download options now appear at once.

- src/client/features/search/index.js
- src/client/services/server-api/index.js
- src/server/pathway-commons/index.js
- src/server/pathway-commons/search/index.js
- src/server/routes/pc.js
- src/styles/features/search.css
Made specific pc search for getting Uniprot IDs instead of piggy backing on the querySearch. Also made changes as to when the box appears and how the text in it is formated.
> Search info box

- src/client/common/components/base-network-view/base-network-view.js
- src/client/common/components/base-network-view/config/menus/file-download.js
- src/client/common/cy/index.js
- src/client/common/cy/interactions-stylesheet.js
- src/client/common/cy/layout/index.js
- src/client/common/cy/stylesheet.js
- src/client/features/index.js
- src/client/features/interactions/index.js
- src/client/features/search/index.js
- src/client/router.js
- src/client/services/server-api/index.js
- src/styles/features/search.css
Basic interaction view that fetches the neighborhood on the client side then cuts the neighborhood to 1 degree (makes the network somewhat more reasonable in size), and colours the edges based on the interaction type.
> Interaction view

- src/client/features/enrichment-map/enrichment.js
- src/client/features/enrichment-map/index.js
- src/client/features/enrichment-map/validator.js
> fill in UI skeleton

- src/client/common/cy/events/hover.js
- src/client/common/cy/interactions-stylesheet.js
- src/client/common/cy/layout/index.js
- src/client/features/search/index.js
- src/styles/features/search.css
Made changes from Issue #457 and #458. The link button is now full width, the layout for the interaction view is now concentric (was grid) and have used debounce on the hover events so the user has to wait to highlight a node/edge.
> Changes to the interaction view 

- src/server/gene-validator/validate-gconvert.js
> modified validatorGconvert to parse g:convert response

- ISSUE_TEMPLATE.md
Add an issue template: see #478
> Adding issue template

- src/server/enrichment-map/enrichment/enrichment.js
- src/server/enrichment-map/enrichment/index.js
> Implement enrichment.js logic

- src/server/enrichment-map/enrichment/enrichment.js
relates to #481 point2, 4
create helper function
remove writing file
> Encapsulate parsing algorithm in a helper function, remove writing files

- package-lock.json
- package.json
> update package.json, package-lock.json for request, csvtojson package

- package.json
> remove 'csvtojson' from package.json

- src/server/enrichment-map/enrichment/enrichment.js
> improved coding style for enrichment service

- src/client/common/config.js
- src/client/common/cy/events/click.js
- src/client/common/cy/events/hover.js
- src/client/common/cy/events/index.js
- src/client/common/cy/events/show-tooltip.js
- src/client/common/cy/index.js
- src/client/features/interactions/index.js
The changes from  interactionViewCombined that relate to tooltips.
- Getting metadata from the extended SIF file for the tooltip
- Added an option to be passed in to base-network-view to enable tooltips on edges or not
- Tooltips now hide when user clicks off the
> Interaction View Tooltips

- test/server/enrichment-map/enrichment/enrichment-test.js
relates to #481 point6
- update path
- Since object keys are unordered, use a helper to check for object equality
> update test for enrichment service

- src/server/enrichment-map/emap/fetchInfo.js
- src/server/enrichment-map/emap/generateCys.js
- src/server/enrichment-map/emap/generateInfo.js
- src/server/enrichment-map/emap/index.js
- src/server/enrichment-map/emap/intersect.js
- src/server/enrichment-map/emap/pathwayTable/index.js
- src/server/enrichment-map/emap/pathwayTable/preprocess.js
> copied emap logic from emap branch

- src/server/enrichment-map/enrichment/enrichment.js
- test/server/enrichment-map/enrichment/enrichment-test.js
relates to #481 point 4
- enrichment.js, use object instead of map
- enrichment-test.js, 't depth', whitespaces in 't name' also change;
> fixed bug in enrichment testing

- test/server/enrichment-map/emap/emap-test.js
> add a basic test for emap service

- src/client/features/enrichment-map/validator.js
- src/client/services/server-api/index.js
> enable UI for validator

- package-lock.json
- src/server/enrichment-map/gene-validator/index.js
relates to #503
- change target database from 'ENSG' to 'HGNC'
- store intialAlias and convertedAlias in output array
> Gconvert bug: target database and output info

- src/server/routes/rest.js
relates to #488 point 6
request url: http://localhost:3000/api/emap/?pathwayIdList=GO:0043525 GO:0043523
> expose an endpoint for emap service

- src/server/enrichment-map/emap/generateCys.js
> remove make_cytoscape call, change variable names in generateCys.js

- src/server/enrichment-map/emap/fetchInfo.js
- src/server/enrichment-map/emap/pathwayTable/preprocess.js
> changed variable names in preprocess.js, fetchInfo.js

- src/server/enrichment-map/emap/pathwayTable/index.js
> fixed variable name in index.js

- src/server/enrichment-map/gene-validator/index.js
> use a fixed version of gconvert

- src/server/enrichment-map/emap/fetchInfo.js
> removed unnecessary checking in fetchInfo.js

- src/server/enrichment-map/gene-validator/index.js
- src/server/routes/rest.js
> exposed target, organism in gconvert validator endpoint

- src/server/routes/rest.js
relates to #481 point8
request url: 
http://localhost:3000/api/enrichment/?genes=TP53 AFF4
http://localhost:3000/api/enrichment/?genes=TP53&setting={%22custbg%22:%20%22CHD1L%20HDAC3%22}
> expose an endpoint for enrichment service

- src/server/enrichment-map/enrichment/enrichment.js
> add custbg parameter in enrichment service default options, comment out test

- src/client/common/components/base-network-view/base-network-view.js
- src/client/features/interactions/filter-menu.js
- src/client/features/interactions/index.js
- src/styles/features/view/graph.css
- src/styles/features/view/sidebarMenu.css
- src/styles/features/view/sidebarMenus/interactionFilterMenu.css
Adds the filter menu to the interaction view.
> Interaction View Filter

- src/client/common/components/base-network-view/base-network-view.js
- src/client/features/interactions/index.js
Removed the repeated declaration of interactionsConfig that occured from the most recent PR and combined the componentWillReciveProps.
> Fixed issues that occured from the last PR 

- src/server/pathway-commons/search/index.js
Made the changes discussed in issue #514.
> Search now uses gene validator to recognize genes.

- src/server/enrichment-map/enrichment/enrichment.js
> throw error when receiving invalid input for enrichment service

- src/server/enrichment-map/enrichment/enrichment.js
> change default options, remove signf from enrichment service

- src/client/features/search/index.js
> Info box links updated

- package-lock.json
- package.json
- src/client/common/components/popover.js
- src/client/common/cy/tooltips/index.js
- src/styles/features/view/toolTip.css
Updated tippy (#555 ) and fixed issue #528 .
> Tippy update

- src/client/services/server-api/index.js
- src/server/pathway-commons/search/index.js
PR #568, broke processPhrase which uses geneValidator this change fixes it.
> Fixed search

- src/server/enrichment-map/enrichment/enrichment.js
> fix enrichment service output bugs

- src/client/common/cy/tooltips/index.js
I missed some changes that needed to be made when updating tippy which caused the show more on tooltips to not function, this fixes that issue.
> Fixed tooltip expand

- src/server/enrichment-map/emap/generateGraphInfo.js
> transform the output of emap service to cytoscape.js format

- src/styles/features/view/toolTip.css
> Tooltip text shrink fix

- src/server/routes/rest.js
> enable post request for emap, validator service

- src/client/features/interactions/filter-menu.js
- src/styles/features/view/sidebarMenus/interactionFilterMenu.css
> Fixed the case where the filter menu colour legend tab would disappear.

- src/server/enrichment-map/gene-validator/index.js
- src/server/enrichment-map/gene-validator/validityInfo.js
- src/server/routes/rest.js
fix a bug in gconvert validator output
send status 400 when error occurs
relates to #591
> Gconvert option

- src/server/enrichment-map/enrichment/enrichment.js
- src/server/routes/rest.js
> added error cases in enrichment service

- src/server/enrichment-map/gene-validator/index.js
#related to #592 
- set prefix to 'ENTREZGENE_ACC'
- when the target namespace is 'NCBIGENE'
- remove prefix in initialAlias
> NCBIGENE should accept and return integer in gene-validator

- test/server/enrichment-map/emap/emap-test.js
- test/server/enrichment-map/enrichment/enrichment-test.js
- test/server/enrichment-map/gene-validator/validate-test.js
> updated tests for distiller

- src/server/enrichment-map/enrichment/enrichment.js
related #614 
- set prefix to 'ENTREZGENE_ACC'
- remove prefix in aAndTList
> NCBI should accept and return integers in enrichment service

- package.json
- src/server/enrichment-map/enrichment/enrichment.js
- src/server/enrichment-map/gene-validator/index.js
> replace 'request' by 'fetch' in gene validation and enrichment service

- src/server/enrichment-map/enrichment/enrichment.js
- src/server/enrichment-map/gene-validator/index.js
> remove options in enrichment, validator response

- src/server/routes/rest.js
> delete get requests

- src/server/routes/rest.js
> change endpoint parameter format in emap service

- src/server/enrichment-map/emap/generateGraphInfo.js
- src/server/enrichment-map/emap/intersect.js
> remove duplicate operations

- src/server/enrichment-map/enrichment/enrichment.js
> refactor parseGprofilerResponse

- src/server/enrichment-map/enrichment/enrichment.js
- src/server/routes/rest.js
> move options conversion to enrichment code

- src/server/enrichment-map/enrichment/enrichment.js
- src/server/routes/rest.js
- add unrecognized, duplicate to enrichment output, related to #537
- remove undefined checking (forgot in pr #655)
> report duplicate, unrecognized from enrichment service

- src/client/services/server-api/index.js
Fix for geneQuery now that it uses post.
> Development fix

- src/styles/features/view/graph.css
> Removed the white space after a sidebar menu is removed.

- src/server/enrichment-map/enrichment/enrichment.js
- src/server/enrichment-map/gene-validator/index.js
add {} in _.assign
related to #661
> fix bugs in _.assign

- src/server/enrichment-map/enrichment/enrichment.js
> remove duplicate, unrecognized from enrichment response

- src/server/enrichment-map/enrichment/enrichment.js
- src/server/enrichment-map/gene-validator/index.js
- src/server/routes/rest.js
related to #667 
allow posting with 
```
{
"genes": "TP53  ATM ATM ATM HGNC:11998  123 123 11111111 ATP  ATM 11111111111",
"target": "ENSG",
"organism": "wwwwwww"
}
```
> allow posting with application/json

- src/server/enrichment-map/enrichment/enrichment.js
- src/server/enrichment-map/gene-validator/index.js
- src/server/enrichment-map/helper/clean-up-entrez.js
- src/server/enrichment-map/helper/index.js
> refactor out trimming rules in vadalition and enrichment service

- src/client/features/interactions/index.js
- src/client/features/search/landing-box.js
The sif viewer now handels uris (issue #647 )
> More general sif viewer

- src/client/common/cy/stylesheet.js
Issue #547 logic nodes now have labels.
> Added labels to logic nodes

- src/client/features/search/index.js
> Search results now wait for landing box

- src/client/features/search/index.js
One of the changes suggested by Gary.
> Changed p53 to TP53 in the search suggestions

- src/client/common/components/base-network-view/base-network-view.js
- src/client/features/interactions/filter-menu.js
- src/client/features/interactions/index.js
- src/styles/features/view/sidebarMenus/interactionFilterMenu.css
@jvwong 
Possible solution to issue #666. Removed checks to indicate a active filter now the legend color only shows when filter is active.
> Interaction legend rework

- src/server/enrichment-map/enrichment/enrichment.js
> modify enrichment output based on Ruth's feedback

- src/client/features/search/landing-box.js
- src/styles/features/search.css
Issue #689 ![screen shot 2018-04-20 at 12 14 53 pm](https://user-images.githubusercontent.com/10948303/39062103-79bf80d8-4494-11e8-8f6b-d7f22f3dccf5.png)
> Landing box id changes

- src/server/enrichment-map/emap/generate-graph-info.js
> change emap output format

- src/server/enrichment-map/gene-validator/index.js
- test/server/enrichment-map/gene-validator/validate-test.js
> fix a bug in validator

- src/server/enrichment-map/enrichment/enrichment.js
- src/server/enrichment-map/gene-validator/index.js
> accept query as array in validation, enrichment service

- src/server/routes/enrichment-rest.js
will revert commit if it doesn't work
> change swagger host to see if it works for testing server

- src/server/routes/enrichment-rest.js
will revert commit if doesn't work
> change host url to see if it works for test server

- src/client/services/server-api/index.js
- src/server/pathway-commons/search/index.js
- src/server/routes/index.js
Fix for issue caused by PR #691 Should be merged with PR #705. Check issue #709  before merging. 
Changes:
- Point geneQuery to right place and pad query.genes
- Pass gene validator an array instead of a string from search
- create a route to enrichment-rest
> Fix to dev by padding the sent array

- src/server/enrichment/analysis/enrichment.js
> analysis service: userThr should be in (0, 1]

- src/client/common/cy/interactions-stylesheet.js
- src/client/features/interactions/index.js
> Highlight Main Node

- package.json
Added my name and email address to the package.json file in the contributors section.
> Added name & email to package.json

- package.json
> Added name and email to list of contributors to package.json

- src/client/features/search/index.js
- src/client/features/search/landing-box.js
- src/styles/features/search.css
- src/styles/features/view/menuBar.css
Add text and/or logo for Pathway Commons on the pathway search and view when the browser is at small widths.
refs: #485
Before:
After:
> Add branding to pathway Search/views @ small-widths (update in feature branch)

- src/client/features/search/landing-box.js
1. Truncate the descriptive text after the conclusion of a sentence rather than by character count or length.
2. The text 'show' and 'hide' should be updated to 'more' and 'less', respectively
refs #733
> Infobox description

- src/client/common/cy/tooltips/format-content.js
- src/client/common/cy/tooltips/index.js
- src/styles/features/view/toolTip.css
It will link to a new pathway commons search for the gene in the tooltip.  The search will open in a new tab.
References #483
> Added link to network view protein tooltips header

- src/client/common/cy/events/show-tooltip.js
> Removed compartment tooltips from view

- src/scripts/datasources/datasources.js
Added a new property called `displayName` and updated dead links in the `homePage` property.
Related to PR #745 as discussed in standup meeting.
> Modified and Updated datasources.js

- src/client/features/search/landing-box.js
- src/styles/features/search.css
Info box description is now always truncated to 2 lines initially. ref: #733
> Infobox description more-less style changes

- src/client/features/search/index.js
- src/styles/features/search.css
New pull request that is up-to-date with PC and includes filter placement changes
> #761 changes to filter placement

- src/client/features/search/index.js
> #784 removal of datasources filter warning

- src/client/features/interactions/index.js
- src/client/features/search/landing-box.js
- src/server/enrichment/validation/index.js
- src/server/enrichment/validation/validity-info.js
- src/server/routes/enrichment-rest.js
- test/server/enrichment/analysis/analysis-test.js
- test/server/enrichment/validation/validation-test.js
- test/server/enrichment/visualization/visualization-test.js
#731 Part 1 for updating general test cases and changing parameter 'target' to 'targetDb'
> Target param change w test cases #731 Part 1

- src/client/features/search/index.js
> correct fix for error message

- src/client/features/search/index.js
#784 This should actually be the fix. We tested the line of code on Rex's computer too and the error disappeared.
> Fix for datasources error 

- src/client/features/search/index.js
> warning fix for the datasources filter 

- src/server/enrichment/analysis/enrichment.js
- src/server/routes/enrichment-rest.js
- test/server/enrichment/analysis/analysis-test.js
/analysis
remove orderedQuery and default to value false
/visualization
similarityCutoff typo and grammar fix
jaccardOverlapWeight description improvement
> Enrichment doc clean up

- src/client/services/server-api/index.js
Addresses portion of #814
'geneQuery' method returns 'enrich' method for validation
if/else case removed
> Create ServerAPI helper method for enrichment endpoints #814

- src/client/common/components/base-network-view/base-network-view.js
- src/client/common/cy/events/expand-collapse.js
- src/client/common/cy/layout/index.js
- src/client/common/cy/layout/stratified.js
- src/client/common/cy/tooltips/format-content.js
- src/client/common/cy/tooltips/index.js
- src/client/common/cy/tooltips/publications.js
- src/client/features/enrichment/index.js
- src/client/features/paint/paint-menu.js
- src/client/features/search/index.js
- src/server/enrichment/analysis/enrichment.js
- src/server/enrichment/validation/index.js
- src/server/graph-generation/biopax-metadata/metadataParserJson.js
- src/server/graph-generation/biopax-metadata/treeTraversal.js
- src/server/index.js
- src/server/pathway-commons/index.js
- src/server/routes/index.js
- src/server/routes/rest.js
(development) `npm run lint` : `✖ 6 problems (6 errors, 0 warnings)`
I tried to focus on the straightforward stuff like missing semicolons and unused variables.  The remaining errors might require more attention.
With these changes, `npm run test` gives `45 passing (59s)`
Refs #834
> Fixed Some Lint errors

- src/server/enrichment/analysis/enrichment.js
- src/server/routes/enrichment-rest.js
- test/server/enrichment/analysis/analysis-test.js
Corrections so parameters is properly sent to G:GOSt, code passes new 'backgroundGenes' test case
> #849 and #847 Create test case for enrich analysis 'backgroundGenes' 

- src/config.js
- src/server/enrichment/analysis/enrichment.js
- src/server/enrichment/validation/index.js
> set gprofiler url as config, http endpoint

- src/client/common/cy/enrichment-stylesheet.js
The style includes (ref : #846 & #845): 
1. Edge width proportional to similarity rate between nodes
2. Node size proprotional to number of genes
> Enrichment network style

- src/client/features/search/index.js
- src/styles/features/search.css
> Removed 'Pathways' Tab from search

- src/server/enrichment/visualization/generate-graph-info.js
> Variable name uses camelCase

- src/client/features/search/query-entity-info.js
> Fix gene card link

- src/client/common/config.js
> 'Uniprot' now 'UniProt'

- src/client/features/pathways/pathways-cy.js
Needed to be added to the `pathway` specific event files.
Refs #868
> Hover Rework added to new pathways view

- src/client/common/cy/events/hover.js
- src/client/features/pathways/pathways-cy.js
> Removed hover highlighting for edges

- src/client/common/cy/enrichment-stylesheet.js
- change enrichment node scaling equation to be linear
> Linear Node Size #936

- src/server/enrichment/validation/index.js
- src/server/routes/enrichment-rest.js
ref #927 
Cache calls to validator based upon (sorted) genes, options
> Cache calls to validator based upon (sorted) genes, options

- src/client/features/pathways/cy/events.js
- src/client/features/pathways/cy/pathways-stylesheet.js
for some reason the hover changes Michael worked on didn't get merged properly, I re added the changes manually.
> hover change re-added after weird merge

- src/client/features/enrichment/enrichment-menu.js
- Insertion of proper link leading users to gProfiler's documentation
- link opens in a new tab
> Proper documentation link #923 revisited

- src/client/common/cy/tooltips/index.js
- src/client/features/paint/pathway-node-metadata.js
- src/client/features/pathways/pathway-node-metadata.js
External database links should open new tab.
> Links in node metadata open new tab

- src/client/features/enrichment/index.js
- close toolbar and side menu when loading
- reopen once network has loaded
> close side menu and toolbar when loading #984

- src/client/features/enrichment/index.js
- src/client/features/interactions/index.js
- src/client/features/interactions/interactions-menu.js
- src/styles/features/enrichment.css
- src/styles/features/interactions.css
- src/styles/features/pathways/app-bar.css
- fix interactions styling after refactor
- change styling in universal app-bar.css file (affects interactions and enrichment); as a result, remove enrichment specific 'enrichment-app-bar' styling and use general 'app-bar' for enrichment
> interactions styling fixes #973

- src/client/features/interactions/cy/index.js
- src/client/features/interactions/cy/interactions-stylesheet.js
- src/client/features/interactions/interactions-toolbar.js
refs #986
Could use some thought as to what the actual matched style should be.  I think there are better options than a yellow overlay for this type of network
> implement interaction node search

- src/client/features/interactions/index.js
> fix interactions bug where a undefined response was being loaded into cytoscape

- src/client/common/components/empty-network.js
- src/client/features/interactions/index.js
- src/client/features/pathways/index.js
- src/styles/common/empty-network.css
> re-add network empty message to interactions and pathways

- src/client/features/enrichment/enrichment-toolbar.js
> implement enrichment toolbar btns

- src/client/features/enrichment/enrichment-download-menu.js
- comment out SIF download button due to current lack of functionality
> Enrichment Remove SIF download  #998

- src/client/features/enrichment/enrichment-toolbar.js
- src/client/features/interactions/interactions-toolbar.js
> general tooltip descriptions for interactions and enrichment

- src/client/features/interactions/interactions-menu.js
> Default slider value fix

- src/client/common/components/empty-network.js
- src/client/features/enrichment/index.js
- src/client/features/interactions/index.js
- src/styles/common/empty-network.css
- src/styles/features/enrichment.css
- indicate if input resulted in empty network
- allow user to edit input
- adjust placement of message when screen width decreases
> empty network view enrichment #976

- src/client/features/enrichment/token-input.js
- do not send empty query to service
- if input contains only spaces and line breaks, do not send to service, 
- if input contains only spaces and line breaks, clear input box
- only send inputs with textual content
> handle empty input #978

- src/client/features/enrichment/cy/enrichment-stylesheet.js
- src/client/features/enrichment/cy/index.js
- src/client/features/enrichment/enrichment-toolbar.js
- src/client/features/enrichment/index.js
- add functionality to search bar in toolbar 
- allow for searching by node label ('description') and 'geneSet'
> Search entities enrichment functionality #992

- src/client/features/search/index.js
- src/styles/features/search.css
> change search result titles to use the plain link css class

- src/client/features/pathways/index.js
> Reversed pathway title format changes

- src/client/features/enrichment/index.js
- src/client/features/interactions/index.js
- src/client/features/pathways/index.js
> render sidebar after any loading has finished

- src/client/features/enrichment/index.js
- src/styles/features/enrichment.css
> Fix changemenu

- src/client/common/components/pc-logo-link.js
- src/client/features/enrichment/index.js
- src/client/features/interactions/index.js
- src/client/features/paint/index.js
- src/client/features/pathways/index.js
- src/client/features/search/index.js
- src/styles/common/index.css
- src/styles/common/pc-logo-link.css
- src/styles/features/pathways/app-bar.css
- src/styles/features/search.css
- removed all instances of hardcoded pathway commons url
- pc-logo link component uses the config PC_URL
- className can be overidden by props
refs #1048
> create a pc-logo link component

- src/styles/features/search.css
> Small viewport styles

- ci.sh
I had some friction getting this to work on Ubuntu. Maybe there's a better way but this works.
> append to PATH in cron; cd into workspace

- src/server/graph-generation/interaction/index.js
related to pattern parameter changes in #1022
> Iss1022 patterns

- src/client/features/enrichment/enrichment-tooltip.js
- src/client/features/interactions/interactions-node-tooltip.js
- src/client/features/paint/pathway-node-metadata.js
- src/client/features/pathways/pathway-node-metadata.js
- src/client/features/search/entity-info-box.js
- src/styles/common/buttons.css
- src/styles/common/cytoscape-tooltip.css
- src/styles/features/entity-landing-box.css
- text for sub fields (name, description, other names) is smaller than the title label
- places the button in the center of the screen
- more padding between interactions results and pathway results
- open to design suggestions
> interactions button and minor entity info box tweaks

- src/client/features/interactions/cy/interactions-stylesheet.js
> hide nodes with 0 degree on the client side of the interactions app

- src/server/graph-generation/interaction/index.js
re #1079 where i was overwriting the node object, destroying degree increments.
Now TP53 looks like this:
> Check if the node has already been added

- src/client/features/interactions/interactions-edge-tooltip.js
- src/server/graph-generation/interaction/index.js
- test/server/interactions/interactions-network-generation-test.js
re #1082 adding datasources for interactions but no link.
> Added datasources but no link

- src/client/features/interactions/cy/index.js
- src/client/features/interactions/interactions-edge-tooltip.js
- src/config.js
- src/server/external-services/ncbi.js
- src/server/graph-generation/interaction/index.js
- test/server/interactions/interactions-network-generation-test.js
- prefetch pub med data for each interaction 
- use a concentric layout for the interactions app
> Pubmedpost

- package-lock.json
- src/client/common/cy/cytoscape-tooltip.js
- src/styles/common/cytoscape-tooltip.css
- place tooltips on the right of the target
- expand max height of tooltips to be 90vh
> space efficient cytoscape tooltips

- src/client/features/paint/pathway-node-metadata.js
- src/client/features/pathways/pathway-node-metadata.js
- src/models/pathway/pathway-node-metadata.js
> show sbgn class as a fallback when the node has no metadata

- src/server/external-services/gprofiler/gconvert/index.js
- src/server/external-services/gprofiler/gprofiler.js
- src/server/external-services/hgnc.js
- src/server/external-services/ncbi.js
- src/server/external-services/pathway-commons.js
- src/server/external-services/uniprot.js
- src/server/index.js
- src/server/routes/factoids/index.js
- src/util/fetch.js
- src/util/index.js
Refs #1121 
- wrapper for global fetch instance to throw on response.ok is false
> Added util called safeFetch

- src/client/features/paint/index.js
- src/client/features/search/entity-summary-box.js
- src/client/services/server-api/index.js
> Replaces client instances fetch

- README.md
- package-lock.json
- package.json
- src/config.js
- src/server/routes/interactions/generate-interactions-image.js
- src/server/routes/interactions/index.js
- add pc img cache config param for img generation
- update documentation to include chromium for image generation
> use cytonsap 3.0.0

- src/client/features/pathways/pathway-node-metadata.js
- src/config.js
- src/server/external-services/pathway-commons.js
- src/server/routes/pathway-commons-router.js
- src/server/routes/pathways/generate-pathway-json/biopax-metadata/index.js
- test/server/pathways/sample-metadata-out.json
refs #1147 
- altered `xref2Uri` to return namespace and URI
- produce pathway metadata `xrefLinks` keyed by namespace
- added namespace to config 
- pathway tooltips updates
> Iss1147 xref links in tooltips

- src/server/external-services/gprofiler/gconvert/index.js
- src/server/external-services/pathway-commons.js
- catch errors in the gconvert entity extraction and return an empty array if if fails
- make the code quality in pathway-commons service more consistent with the rest of the codebase
refs #1137
> Search timeout handling

- src/server/external-services/pathway-commons.js
refs #1160 - filter out empty pathways
> filtering empty pathways

- src/client/features/enrichment/cy/index.js
- src/client/features/enrichment/enrichment-tooltip.js
> enrichment tooltips are more stable

- package-lock.json
- package.json
- src/client/cytoscape-extensions.js
- src/client/features/enrichment/cy/enrichment-stylesheet.js
- src/client/features/enrichment/cy/index.js
- src/client/features/enrichment/enrichment-toolbar.js
refs #1153 
- use cola layout as it seems to produce better results for enrichment networks ( disconnected components)
- don't show text labels for the network until the user is zoomed past a specific font size
- edges and node styles are more consistent with the interactions app
- change the 'fit' button to be animated 
- add selection style for nodes and edges
> Enrichment style

- src/client/features/paint/cy/actions.js
- src/client/features/paint/demo-pathway-results.json
- src/client/features/paint/expression-table.js
- src/client/features/pathways/cy/actions.js
- src/models/pathway/pathway-model.js
- src/server/routes/pathways/generate-pathway-json/biopax-metadata/index.js
- test/server/pathways/sample-cyjson-out.json
remove the 'geneSynonyms' pathway node data field and merge it with  the pathway node metadata.synonyms field
refs #1173
> merge geneSynonyms into the metadata.synonyms field

- src/client/features/interactions/interactions-download-menu.js
> dont use json stringify for the sif text

- src/server/external-services/pathway-commons.js
- src/server/routes/index.js
- src/server/routes/search/index.js
- src/server/routes/search/search.js
> Iss1156 unified search

- package-lock.json
- package.json
Not necessary right away, but it's nice to upgrade for testing etc.
> Update to cytoscape@3.3.0

- src/server/cache.js
> Dropped arg for defaultGetKey

- src/server/routes/search/search.js
Should fix tokenize bug in #1216 PR.
> Fixed tokenize regex bug

- src/server/external-services/gprofiler/gprofiler.js
- src/server/routes/enrichment/visualization/index.js
- visualization results are simpler
> tweak enrichment opts to prune the enrichment network

- src/client/features/enrichment/enrichment-download-menu.js
- src/client/features/enrichment/index.js
> fix broken enrichment downloads #1237

- src/client/features/interactions/index.js
refs #1242 
enrichment style title for interactions
> interactions title truncation for long gene lists

- src/client/features/paint/index.js
> update painter to use the new search api

- src/client/features/paint/index.js
- src/client/features/paint/menus/paint-menu.js
- src/client/features/paint/pathway-node-metadata.js
- src/models/pathway/pathway-model.js
- src/styles/features/paint.css
refs #1253
need to fix this before the enrichment map app release in January
> Paint fixes

- package-lock.json
- src/client/features/interactions/interactions-edge-tooltip.js
refs #1259 
publications list wasnt being loaded when there was only one edge, leading to the infinite loading spinner
> fix interactions edge render logic when there is only one edge

- package-lock.json
- package.json
We don't have time to test with 3.3 for the upcoming release, so let's use the older version.  We're not using any new features yet, anyway.
> Switch to cytoscape@3.2.22

- src/client/features/search/gene-results-view.js
- src/client/features/search/index.js
- src/styles/features/search.css
- src/styles/vars.css
- Styling improvements for mobile & smaller windows
- Better example queries
- Better use of space for the app linkout cards
> Improvements to search page

- src/client/features/search/index.js
- src/client/features/search/pathway-results-view.js
Removes the datasource filter and pathway participant size (gt/lt) params. 
Refs #1272
> Removing search filter and participant query params

- src/client/common/components/error-message.js
- src/client/features/pathways/index.js
- src/client/services/server-api/index.js
- src/config.js
- src/styles/common/error-message.css
- Longer (15s) timeout for Pathways viewer
- Error message on timeout or empty network 
- Error now links back to search via logo
refs #1274
> Issue: 1274: Relax timeouts for Pathways

- src/client/features/search/gene-results-view.js
Enrichment threshold set at 5 or more genes.
Refs #1282.
> App card minimum gene thresholds for display in search. 

- src/client/features/enrichment/index.js
Displaying timeout and error message, same as before (#1278). 
refs #1210.
> Error handling: Enrichment

- Dockerfile
- README.md
> Jvwong iss1287 readme

- src/client/common/components/error-message.js
- src/client/features/enrichment/index.js
- src/client/features/interactions/index.js
- src/client/features/search/index.js
- src/styles/common/error-message.css
Fixes typos in error message. Add a branded link back to search page. 
refs #1299
> Add pc search branding; typos corrected

- src/client/features/search/pathway-results-view.js
Typo in last PR.
Related to #1305
> Typo in datasource filter

- src/client/features/enrichment/index.js
- src/client/features/pathways/menus/network-info-menu.js
Cleanup:
1. Unique key on pathway network-info-menu.js comments
2. Unique key warning on enrichment component
> Cleanup: React warnings

- src/client/features/pathways/menus/file-download-menu.js
- src/styles/common/menus.css
Instead of hanging spinner, download menu displays error message.
Refs #1312
> Show error message on file download fetch error.

- .travis.yml
> Travis: Drop rethink in config

- src/server/routes/search/search.js
Remove quotes in gene search tokenization.
Refs #1248
> Drop outside quotes for any tokens.

- src/client/features/search/index.js
> Removed gt, lt params from search query.

- src/config.js
- src/server/routes/enrichment/visualization/pathway-table.js
- src/server/routes/enrichment/visualization/update-enrichment.js
> Put GMT_ARCHIVE_URL in config

- src/client/features/enrichment/index.js
- src/client/features/interactions/index.js
> Describing genes in title bar

- src/config.js
Addresses Mixed Content errors downloading files from PC.
Refs #1342.
> Make calls to secure pc url.

- test/server/summary/hgnc/entity-summary-TP53.json
- test/server/summary/hgnc/entity-summary-test.js
- test/server/summary/ncbi/entity-summary-7157.json
- test/server/summary/ncbi/entity-summary-test.js
- test/server/summary/uniprot/entity-summary-Q99988.json
Addresses failed tests in #1343.
> Update tests for changes in #1343.

- README.md
- package-lock.json
- package.json
- src/client/features/enrichment/index.js
- src/client/features/interactions/index.js
- src/config.js
- src/server/routes/enrichment/visualization/pathway-table.js
- src/server/routes/enrichment/visualization/update-enrichment.js
- test/server/summary/hgnc/entity-summary-TP53.json
- test/server/summary/hgnc/entity-summary-test.js
- test/server/summary/ncbi/entity-summary-7157.json
- test/server/summary/ncbi/entity-summary-test.js
- test/server/summary/uniprot/entity-summary-Q99988.json
Minor changes:
- File download errors (upgrade to https)
- App title gene list rendering
- Config for GMT archive URL
> Version 3.1.1

- src/client/features/pathways/pathway-node-metadata.js
Provide defaults for display data; hide if missing or empty.
Refs #1355
> Pathway node tooltips

- .travis.yml
- package-lock.json
- package.json
- src/client/features/interactions/interactions-node-tooltip.js
- src/client/features/pathways/pathway-node-metadata.js
- src/server/external-services/gprofiler/gconvert/index.js
- src/server/routes/enrichment/index.js
- src/server/routes/factoids/index.js
- src/server/routes/search/search.js
- test/server/enrichment/validation/validation-test.js
Notes:
Major:
- Updates to enrichment/validation api
Minor:
- Bug fixes incl. for 'factoids' support
> Release version 3.3.0

- src/client/features/enrichment/cy/index.js
> Only add cluster parent if doesn't exist.

- src/client/features/enrichment/index.js
- src/client/features/interactions/index.js
- src/client/features/pathways/index.js
- src/client/features/pathways/menus/file-download-menu.js
- src/client/features/search/index.js
> Clear any errors if fetch is successful.

- package-lock.json
- package.json
- src/scripts/batch/.eslintrc.js
- src/scripts/batch/hit_counts.js
- src/scripts/batch/test.csv
- src/server/external-services/pathway-commons.js
- src/server/routes/search/search.js
- src/util/fetch.js
- this is e.g., to run all those query strings from a Reactome's monthly "failed user's search" report through our PC apps flow and compare, analyse, celebrate or cry the differences...
> Batch node search, count (pathways and SIFs) script

- .env
- Dockerfile
- README.md
- dev-compose.yml
including auto-updating of the generic entities metadata from the PC downloads
during the image build.
> Can now rebuild and run this app at once using either Docker or Compose,

- .gitignore
- src/config.js
- src/server/routes/enrichment/visualization/pathway-table.js
- src/server/routes/enrichment/visualization/update-enrichment.js
- src/server/source-files.js
- test/server/enrichment/visualization/visualization-test.js
- By default, archived GMT source files are fetched and placed in a top-level `downloads` folder 
- Enrichment app visualization module streams in GMT directly to a Map, dispensing with the `pathways.gmt` file intermediary
- updated tests
Refs #1378
> Iss1378 handle downloaded files

- src/styles/features/search.css
This fixes the scroll issue, as mentioned by email, on mobile devices.  It also addresses a couple of related alignment issues.
> Scroll fix

- src/server/external-services/ncbi.js
> Add user agent to calls to NCBI

- README.md
Tested range for nodejs version - works below 11 and above 10.
Refs #1397
> Document NodeJS versions

- src/server/routes/pathways/generate-pathway-json/biopax-metadata/index.js
This was a bug in accessing an object vs Map. 
Refs #1399
> Access to Map of generic physical entities.

- src/config.js
- src/server/routes/interactions/generate-interactions-json.js
The goal here was to bias the interactions app to show interactions from Biofactoid, which, in all likelihood will be the most recently identified anyways.
This PR is rather heavy-handed (i.e. just pushes biofactoids to the top of the pile), and maybe there's other ways? 
Refs #1269
> Biofactoid-derived interactions

- package-lock.json
- package.json
Changes: Prioritize Biofactoid interactions
> Version 3.5.0

- src/client/common/components/app-card.js
- src/client/common/components/index.js
- src/client/features/search/gene-results-view.js
- src/styles/common/app-card.css
- src/styles/common/index.css
- src/styles/features/search.css
Made the `app-linkout` items (Interactions, Enrichment) an `AppCard` React component. Refactored the search page to use these.
Wide display:
Narrow:
Refs #1401
> AppCard component

- package-lock.json
- package.json
- src/client/router.js
- src/views/index.html
> Google Analytics 4

- package-lock.json
- package.json
> Tag v3.7.0

- src/client/common/components/pc-logo-link.js
- src/client/features/search/gene-results-view.js
- src/client/features/search/index.js
- src/styles/features/search.css
Just taking the changes from the other PR and basing them from the dev branch rather than master.
Ref:
- #1435
> Dev branch redo: More explanation, links for new visitors

- src/client/common/components/contribute.js
- src/client/features/enrichment/index.js
- src/client/features/interactions/index.js
- src/client/features/pathways/index.js
- src/client/features/search/index.js
- src/styles/common/contribute.css
- src/styles/common/index.css
- src/styles/features/search.css
Prototype for link out to Biofactoid: A `Contribute` component. Uses the Biofactoid `/document/new` route.
Here it's in the Interactions app, and could also be placed in the pathways viewer, maybe the enrichment app. Not sure about the main search page.
**Interactions app**
Refs #1434
> Iss1434 contribute your data

- src/client/features/search/index.js
Point the example to adhesion related pathways (i.e. Biofactoid-rich documents will come up, look nice).
Refs #1416
> Updated search query examples.

- src/client/common/components/contribute.js
- src/client/features/search/feature-view.js
- src/client/features/search/index.js
- src/server/external-services/pathway-commons.js
- src/styles/common/app-bar.css
- src/styles/common/contribute.css
- src/styles/features/search.css
- Simplfications:
- In image overlay, show author caption, otherwise default to canned interaction template text
- Remove nested anchors in overlay
- Misc styling
**e.g. 1: Caption available**
**e.g. 2: No caption available**
Refs #1462
> Simplify feature styling
